### ISSUE TITLE
little bug ?

### ISSUE THREAD

**Issue by Celtic4785** [SnejPro/check_synology#13]
Hello! 
Great plugin. 
But the "storage" is not ok.

./check_synology.py -H 10.31.24.52 -u x -a x -p x -m storage

Traceback (most recent call last):
  File "./check_synology.py", line 508, in <module>
    render_storage(queue)
  File "./check_synology.py", line 404, in render_storage
    size_bytes = int(r['1.3.6.1.2.1.25.2.3.1.4.'+id]['value'])*int(r['1.3.6.1.2.1.25.2.3.1.5.'+id]['value'])
KeyError: '1.3.6.1.2.1.25.2.3.1.4.56'

snmapwalk:
.1.3.6.1.2.1.25.2.3.1.4.1 = INTEGER: 1024
.1.3.6.1.2.1.25.2.3.1.4.3 = INTEGER: 1024
.1.3.6.1.2.1.25.2.3.1.4.6 = INTEGER: 1024
.1.3.6.1.2.1.25.2.3.1.4.7 = INTEGER: 1024
.1.3.6.1.2.1.25.2.3.1.4.8 = INTEGER: 1024
.1.3.6.1.2.1.25.2.3.1.4.10 = INTEGER: 1024
.1.3.6.1.2.1.25.2.3.1.4.31 = INTEGER: 4096
.1.3.6.1.2.1.25.2.3.1.4.36 = INTEGER: 4096
.1.3.6.1.2.1.25.2.3.1.4.38 = INTEGER: 4096
.1.3.6.1.2.1.25.2.3.1.4.39 = INTEGER: 4096
.1.3.6.1.2.1.25.2.3.1.4.49 = INTEGER: 4096
.1.3.6.1.2.1.25.2.3.1.4.55 = INTEGER: 8192
.1.3.6.1.2.1.25.2.3.1.4.56 = INTEGER: 4096

.1.3.6.1.2.1.25.2.3.1.5.1 = INTEGER: 2034260
.1.3.6.1.2.1.25.2.3.1.5.3 = INTEGER: 5351936
.1.3.6.1.2.1.25.2.3.1.5.6 = INTEGER: 2034260
.1.3.6.1.2.1.25.2.3.1.5.7 = INTEGER: 1325860
.1.3.6.1.2.1.25.2.3.1.5.8 = INTEGER: 71004
.1.3.6.1.2.1.25.2.3.1.5.10 = INTEGER: 3317676
.1.3.6.1.2.1.25.2.3.1.5.31 = INTEGER: 596382
.1.3.6.1.2.1.25.2.3.1.5.36 = INTEGER: 254282
.1.3.6.1.2.1.25.2.3.1.5.38 = INTEGER: 254282
.1.3.6.1.2.1.25.2.3.1.5.39 = INTEGER: 254282
.1.3.6.1.2.1.25.2.3.1.5.49 = INTEGER: 254282
.1.3.6.1.2.1.25.2.3.1.5.55 = INTEGER: 1404790756
.1.3.6.1.2.1.25.2.3.1.5.56 = INTEGER: 3897958

It's a RS815+ NAS with DSM 7.1-42661 Update 1

load,memory, disk, raid, status, update is ok, thx.

**Comment by SnejPro** [comment]
I will have a look at it over the next few days.
Do you have one or more volumes/pools?

**Comment by Celtic4785** [comment]
I apologize for the delay. Sorry to respond late.
I switched to this repository that day:
https://github.com/okrouhly/check_synology

that works perfectly.

**Comment by Celtic4785** [comment]
> I will have a look at it over the next few days. Do you have one or more volumes/pools?

one pool. RAID 5, 4 disks.

**Comment by SnejPro** [comment]
Hi, i've did a complete rewrite in May. Have you used the most recent version?
