### ISSUE TITLE
TypeError: must be str, not NoneType

### ISSUE THREAD

**Issue by Optimaximal** [SnejPro/check_synology#16]
Downloaded v1 and deployed it to my Icinga2 server (Ubuntu 18.04).

When I attempt to execute the script from the command line, I get the following:

`Traceback (most recent call last):`
`File "./check_synology.py", line 53, in <module>`
`last_check_file = "/tmp/check_synology_"+args.hostname+"_"+re.sub('\W', '', args.mode)+".json"`
`TypeError: must be str, not NoneType`

I'm not a python guy, so what's the easy fix here?

edit - just to confirm, is this compatible with DSM 7?

**Comment by SnejPro** [comment]
Hi,

have you entered a hostname?

`./check_synology.py` will not work. You have to enter `./check_synology.py -H <Hostname or IP-Adress>`

**Comment by Optimaximal** [comment]
🤦‍♂️ I was expecting an appropriate error message or help to load by default, like the other Synology script that's not DSM7 compatible. My bad for making assumptions.

Still, getting the following once I run `./check_synology.py -H 'IP ADDRESS' -m all`...

`Traceback (most recent call last):`
`  File "./check_synology.py", line 483, in <module>`
`    fetch_required_values()`
`  File "./check_synology.py", line 481, in fetch_required_values`
`    run_queue()`
`  File "./check_synology.py", line 236, in run_queue`
`    snmp_result = snmpget(queue["get"])`
`  File "./check_synology.py", line 226, in snmpget`
`    snmpres = run_snmp("snmpget", oids)`
`  File "./check_synology.py", line 110, in run_snmp`
`    result=subprocess.run(command, capture_output=True).stdout.decode('UTF-8')`
`  File "/usr/lib/python3.6/subprocess.py", line 423, in run`
`    with Popen(*popenargs, **kwargs) as process:`
`TypeError: __init__() got an unexpected keyword argument 'capture_output'`

**Comment by RincewindsHat** [comment]
Same here, I did not add any authentication hints, so the plugin assumed `SNMPv3` (`2c` is used) and it died with the same error instead of telling me, that I have an authentication problem.
